# Generated by Django 6.0.7 on 2026-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
