# Generated by Django 6.0.7 on 2026-08-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_membros_cidade_membros_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('nivel_vergonha', models.IntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Médio'), (4, '4 - Alto'), (5, '5 - Extremo')])),
                ('nivel_graca', models.IntegerField(choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Médio'), (4, '4 - Alto'), (5, '5 - Extremo')])),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Membros',
        ),
    ]
