# Generated by Django 6.1 on 2026-08-07 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_historiaerro_delete_membros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('graca', '😂 Engraçado'), ('vergonha', '😳 Vergonha')], max_length=10)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='membros.historiaerro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('historia', 'usuario')},
            },
        ),
    ]
