# Generated by Django 6.1 on 2026-08-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_historiaerro_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacao',
            name='tipo',
            field=models.CharField(choices=[('graca', '😂'), ('triste', '😢'), ('coracao', '❤️'), ('raiva', '😡')], max_length=10),
        ),
    ]
