# Generated by Django 6.1 on 2026-08-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0006_alter_reacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaerro',
            name='nivel_graca',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Médio'), (4, '4 - Alto'), (5, '5 - Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='historiaerro',
            name='nivel_vergonha',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Muito baixo'), (2, '2 - Baixo'), (3, '3 - Médio'), (4, '4 - Alto'), (5, '5 - Extremo')], null=True),
        ),
    ]
