# Generated by Django 6.1 on 2026-09-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
